- methodology  
https://english.sse.com.cn/indices/indices/list/indexmethods/c/000688_000688hbooken_EN.pdf
- STAR market  
https://english.sse.com.cn/markets/equities/overview/

In [1]:
from help import *

In [2]:
url = "https://yunhq.sse.com.cn:32042//v1/sh1/list/exchange/kshare"
params = {
    "callback": "jQuery36001552746358891326_1778061972837",
    "select": "code,name,region,pinyin",
    "_": "1778061972839",
}
headers = {
    "Accept": "*/*",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Connection": "keep-alive",
    "Referer": "https://english.sse.com.cn/",
    "Sec-Fetch-Dest": "script",
    "Sec-Fetch-Mode": "no-cors",
    "Sec-Fetch-Site": "same-site",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    "sec-ch-ua": '"Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Linux"',
}
cookies = {
    "gdp_user_id": "gioenc-a886c183,d2e7,500a,c17d,d43c09de8d25",
    "ba17301551dcbaf9_gdp_session_id": "9aefd9bb-3dad-4932-ba71-1aa9d0809f60",
    "ba17301551dcbaf9_gdp_session_id_sent": "9aefd9bb-3dad-4932-ba71-1aa9d0809f60",
    "ba17301551dcbaf9_gdp_sequence_ids": '{"globalKey":147,"VISIT":6,"PAGE":24,"VIEW_CLICK":119}',
}

response = requests.get(url, params=params, headers=headers, cookies=cookies)
print(response.status_code)

200

In [3]:
s = response.text

In [4]:
t = pd.DataFrame(json.loads(s[s.find('{'):s.find('}')+1])['list'], columns=['stock_code', 'cn_name', 'cn1', 'en'])

In [5]:
t['stock_code'] = t['stock_code'].astype(int)

In [6]:
t[
	(t['stock_code']>=688000) & 
	(t['stock_code']<=688999)
	]

     stock_code cn_name  cn1    en
0        688001    华兴源创  江苏省  HXYC
1        688002    睿创微纳  山东省  RCWN
2        688003    天准科技  江苏省  TZKJ
3        688004    博汇科技  北京市  BHKJ
4        688005    容百科技  浙江省  RBKJ
..          ...     ...  ...   ...
603      688816     易思维  浙江省   YSW
604      688818    电科蓝天  天津市  DKLT
605      688819    天能股份  浙江省  TNGF
606      688820    盛合晶微       SHJW
607      688981    中芯国际       ZXGJ

[608 rows x 4 columns]

In [7]:
t[(~(t['stock_code']>=688000)) | (~(t['stock_code']<=688999))]

     stock_code cn_name cn1    en
608      689009    九号公司      JHGS

In [9]:
t.to_csv('star_board.csv', index=False)

In [10]:
t

     stock_code cn_name  cn1    en
0        688001    华兴源创  江苏省  HXYC
1        688002    睿创微纳  山东省  RCWN
2        688003    天准科技  江苏省  TZKJ
3        688004    博汇科技  北京市  BHKJ
4        688005    容百科技  浙江省  RBKJ
..          ...     ...  ...   ...
604      688818    电科蓝天  天津市  DKLT
605      688819    天能股份  浙江省  TNGF
606      688820    盛合晶微       SHJW
607      688981    中芯国际       ZXGJ
608      689009    九号公司       JHGS

[609 rows x 4 columns]

- analyze etf constituents